from django.db import models

# Create your models here.
'''
The User model corresponds to users of the API and has the fields, username, which is provided by the user,
api_token which is generated by the API and is_admin which defines if it is an admin account
'''
class User(models.Model):
	username = models.CharField(primary_key = True, max_length = 20)
	api_token = models.CharField(max_length = 50)
	is_admin = models.BooleanField()

'''
The Occurrence model describes occurrences added by the users. It has an id (occ_id), a description,
a location (defined as latitude and longitude), a user, a date and time of creation, the date and time of its last update,
its status and the category of the occurrence
'''
class Occurrence(models.Model):
	occ_id = models.AutoField(primary_key = True)
	description = models.CharField(max_length = 200)
	latitude = models.DecimalField(max_digits = 14, decimal_places = 10)
	longitude = models.DecimalField(max_digits = 14, decimal_places = 10)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	creation_date = models.DateTimeField()
	update_date = models.DateTimeField(blank = True, null = True)
	status = models.CharField(max_length = 20)
	category = models.CharField(max_length = 20)